# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe3fff87cc656d85eb974800034fc9fc844ce96801aa36b2d262226e4e39ef3e84985f91d323dabb1dfe2612ff8ced5be5486e921ee7f5f0228054eb04dcf4d3

test:
  secret_key_base: f7b0f5fb6452ed8bb695a8a2ce76fecdfc8ec79055470182fe1b2c3f4f01e8371305656b4ee41ae37324d8d91e9b452174000a2bc1301101e6b15596af6413ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
